version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    build: ./order
    image: europe-west4-docker.pkg.dev/versatile-field-350813/web-scale-repository/order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/order_redis.env
      - env/order_postgres.env

  order-postgres-service:
    image: postgres:14.1-alpine
    env_file:
      - env/order_postgres.env

  stock-service:
    build: ./stock
    image: europe-west4-docker.pkg.dev/versatile-field-350813/web-scale-repository/stock:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/stock_redis.env
      - env/stock_postgres.env

  stock-postgres-service:
    image: postgres:14.1-alpine
    env_file:
      - env/stock_postgres.env

  payment-service:
    build: ./payment
    image: europe-west4-docker.pkg.dev/versatile-field-350813/web-scale-repository/user:latest
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/payment_redis.env
      - env/payment_postgres.env

  payment-postgres-service:
    image: postgres:14.1-alpine
    env_file:
      - env/payment_postgres.env
