apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    type: app-service
spec:
  type: ClusterIP
  selector:
    component: order
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: order
  template:
    metadata:
      labels:
        component: order
    spec:
      containers:
        - name: order
          image: ptemarvelde/wdm-2022:order
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: [ "uvicorn" ]
          args: [ "app:app", "--host", "0.0.0.0", "--port", "5000" ]
          ports:
            - containerPort: 5000
          env:
            - name: GATEWAY_URL
              value: "nginx-ingress-nginx-controller"
            - name: PAYMENT_SERVICE_URL
              value: "payment-service:5000"
            - name: STOCK_SERVICE_URL
              value: "stock-service:5000"
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_DB
              value: 'order_db'
            - name: POSTGRES_HOST
              value: "order-postgres-service"
            - name: POSTGRES_REPLICA_HOST
              value: "order-postgres-service-replica"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp/prometheus"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    release: promstack
spec:
  selector:
    matchLabels:
      type: app-service
  endpoints:
    - targetPort: 5000
      path: "/metrics"
      interval: 5s
