apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-queue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment-queue
  template:
    metadata:
      labels:
        component: payment-queue
    spec:
      containers:
        - name: payment-queue
          image: ptemarvelde/wdm-2022:payment-queue
          imagePullPolicy: Always
          resources:
            limits:
              memory: "250Mi"
              cpu: "750m"
            requests:
              memory: "100Mi"
              cpu: "250m"
          command: [ "python" ]
          args: [ "consumer.py" ]
          env:
            - name: GATEWAY_URL
              value: "nginx-ingress-nginx-controller"
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_DB
              value: 'user_db'
            - name: POSTGRES_HOST
              value: "user-postgres-service"
            - name: POSTGRES_REPLICA_HOST
              value: "user-postgres-service-replica"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp/prometheus"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment-queue-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-queue-deployment
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 60
