apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: stock-postgres-service
  namespace: default

spec:
  replicas: 3
  image: postgres:14.1

  customConfig: custom-postgres-config

  database:
    size: 200Mi

  env:
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: PGPASSWORD
      value: "postgres"
    - name: POSTGRES_REPLICATION_PASSWORD
      value: "postgres"
    - name: DB_NAME
      value: "stock_db"
    - name: CREATE_TABLE_QUERY
      value: >
        CREATE TABLE stock (
          user_id serial PRIMARY KEY,
          username VARCHAR ( 50 ) UNIQUE NOT NULL,
          password VARCHAR ( 50 ) NOT NULL,
          email VARCHAR ( 255 ) UNIQUE NOT NULL,
          created_on TIMESTAMP NOT NULL,
              last_login TIMESTAMP
        )