apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-queue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stock-queue
  template:
    metadata:
      labels:
        component: stock-queue
    spec:
      containers:
        - name: stock-queue
          image: ptemarvelde/wdm-2022:stock-queue
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: [ "python" ]
          args: [ "consumer.py" ]
          env:
            - name: GATEWAY_URL
              value: "nginx-ingress-nginx-controller"
            - name: PAYMENT_SERVICE_URL
              value: "payment-service:5000"
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_DB
              value: 'stock_db'
            - name: POSTGRES_HOST
              value: "stock-postgres-service"
            - name: POSTGRES_REPLICA_HOST
              value: "stock-postgres-service-replica"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp/prometheus"

