apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    component: user
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    type: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
  template:
    metadata:
      labels:
        component: user
    spec:
      containers:
        - name: user
          image: ptemarvelde/wdm-2022:user
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: [ "uvicorn" ]
          args: [ "app:app", "--host", "0.0.0.0", "--port", "5000" ]
          ports:
            - containerPort: 5000
          env:
            - name: GATEWAY_URL
              value: "nginx-ingress-nginx-controller"
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_DB
              value: 'user_db'
            - name: POSTGRES_HOST
              value: "user-postgres-service"
            - name: POSTGRES_REPLICA_HOST
              value: "user-postgres-service-replica"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp/prometheus"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50