{
 "title": "Monitor services temp",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stock service: Average time per endpoint",
   "type": "timeseries",
   "description": "Average time taken per request to the stock service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(remove_stock_sum[$__rate_interval]) / rate(remove_stock_count[$__rate_interval])",
     "legendFormat": "time_per_remove_stock"
    },
    {
     "expr": "rate(add_stock_sum[$__rate_interval]) / rate(add_stock_count[$__rate_interval])",
     "legendFormat": "add stock"
    },
    {
     "expr": "rate(find_item_sum[$__rate_interval]) / rate(find_item_count[$__rate_interval])",
     "legendFormat": "find item"
    },
    {
     "expr": "rate(create_item_sum[$__rate_interval]) / rate(create_item_count[$__rate_interval])",
     "legendFormat": "create item"
    },
    {
     "expr": "rate(db_update_stock_sum[$__rate_interval]) / rate(db_update_stock_count[$__rate_interval])",
     "legendFormat": "update stock"
    }
   ]
  },
  {
   "title": "Stock service: Count per endpoint",
   "type": "timeseries",
   "description": "Average time taken per request to the stock service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(checkout_items_count[$__rate_interval])",
     "legendFormat": "checkout"
    },
    {
     "expr": "rate(remove_stock_count[$__rate_interval])",
     "legendFormat": "time_per_remove_stock"
    },
    {
     "expr": "rate(add_stock_count[$__rate_interval])",
     "legendFormat": "add stock"
    },
    {
     "expr": "rate(find_item_count[$__rate_interval])",
     "legendFormat": "find item"
    },
    {
     "expr": "rate(create_item_count[$__rate_interval])",
     "legendFormat": "create item"
    }
   ]
  },
  {
   "title": "Order service: Average time per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(rate(checkout_sum[$__rate_interval]) / rate(checkout_count[$__rate_interval]))",
     "legendFormat": "checkout"
    },
    {
     "expr": "(rate(create_order_sum[$__rate_interval]) / rate(create_order_count[$__rate_interval]))",
     "legendFormat": "create_order"
    },
    {
     "expr": "(rate(remove_order_sum[$__rate_interval]) / rate(remove_order_count[$__rate_interval]))",
     "legendFormat": "remove_order"
    },
    {
     "expr": "(rate(add_item_sum[$__rate_interval]) / rate(add_item_count[$__rate_interval]))",
     "legendFormat": "add_item"
    },
    {
     "expr": "(rate(find_order_sum[$__rate_interval]) / rate(find_order_count[$__rate_interval]))",
     "legendFormat": "find_order"
    },
    {
     "expr": "(rate(handle_rollback_metric_sum[$__rate_interval]) / rate(handle_rollback_metric_count[$__rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Order service: Number of requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(checkout_count[$__rate_interval])",
     "legendFormat": "checkout"
    },
    {
     "expr": "rate(create_order_count[$__rate_interval])",
     "legendFormat": "create_order"
    },
    {
     "expr": "rate(remove_order_count[$__rate_interval])",
     "legendFormat": "remove_order"
    },
    {
     "expr": "rate(add_item_count[$__rate_interval])",
     "legendFormat": "add_item"
    },
    {
     "expr": "rate(find_order_count[$__rate_interval])",
     "legendFormat": "find_order"
    }
   ]
  },
  {
   "title": "Payment service: Average time per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(rate(create_user_sum[$__rate_interval]) / rate(create_user_count[$__rate_interval]))",
     "legendFormat": "create user"
    },
    {
     "expr": "(rate(find_user_sum[$__rate_interval]) / rate(find_user_count[$__rate_interval]))",
     "legendFormat": "find user"
    },
    {
     "expr": "(rate(add_credit_sum[$__rate_interval]) / rate(add_credit_count[$__rate_interval]))",
     "legendFormat": "add_credit"
    },
    {
     "expr": "(rate(remove_credit_sum[$__rate_interval]) / rate(remove_credit_count[$__rate_interval]))",
     "legendFormat": "remove credit"
    },
    {
     "expr": "(rate(cancel_payment_sum[$__rate_interval]) / rate(cancel_payment_count[$__rate_interval]))",
     "legendFormat": "cancel payment"
    },
    {
     "expr": "(rate(payment_status_sum[$__rate_interval]) / rate(payment_status_count[$__rate_interval]))",
     "legendFormat": "payment status"
    },
    {
     "expr": "(rate(db_cancel_payment_sum[$__rate_interval]) / rate(db_cancel_payment_count[$__rate_interval]))",
     "legendFormat": "cancel payment"
    }
   ]
  },
  {
   "title": "Payment service: Number of requests per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(create_user_count[$__rate_interval])",
     "legendFormat": "create user"
    },
    {
     "expr": "rate(find_user_count[$__rate_interval])",
     "legendFormat": "find user"
    },
    {
     "expr": "rate(add_credit_count[$__rate_interval])",
     "legendFormat": "add_credit"
    },
    {
     "expr": "rate(remove_credit_count[$__rate_interval])",
     "legendFormat": "remove credit"
    },
    {
     "expr": "rate(cancel_payment_count[$__rate_interval])",
     "legendFormat": "cancel payment"
    },
    {
     "expr": "rate(payment_status_count[$__rate_interval])",
     "legendFormat": "payment status"
    }
   ]
  }
 ]
}